site_name: DataDistillr

nav:
  - Welcome: README.md
  - Getting Started: 
    - Getting Started: getting-started/README.md
    - Create Your Account: getting-started/create-your-account.md
    - Create Your First Project: getting-started/create-your-first-project.md
    - Connecting a Data Source and Uploading a File : getting-started/connecting-a-data-source-and-uploading-a-file.md
    - Running a Query: getting-started/running-a-query.md
    - Visualizing Your Data: getting-started/visualizing-your-data.md
    - Publishing Your Data: getting-started/publishing-your-data.md
  - Connecting Data: 
    - Connecting Your Data To Datadistillr: 
      - Connecting Your Data: connecting-data/connecting-your-data-to-datadistillr/README.md 
      - Uploading Files: connecting-data/connecting-your-data-to-datadistillr/uploading-files.md
      - Connecting Databases: 
        - Connecting Databases: connecting-data/connecting-your-data-to-datadistillr/connecting-databases/README.md
        - Connect To Splunk: connecting-data/connecting-your-data-to-datadistillr/connecting-databases/connecting-to-splunk.md
      - Connecting To Remote Storage: connecting-data/connecting-your-data-to-datadistillr/connecting-to-remote-storage.md
      - Connect To APIs And External Data:
        - Connect to APIs: connecting-data/connecting-your-data-to-datadistillr/connecting-to-apis-and-external-data/README.md
        - Connection Basics: connecting-data/connecting-your-data-to-datadistillr/connecting-to-apis-and-external-data/connection-basics.md
        - Passing Parameters: connecting-data/connecting-your-data-to-datadistillr/connecting-to-apis-and-external-data/passing-parameters.md
  
    - Linking Data To Your Project: connecting-data/linking-data-to-your-project.md
  - ❓ Getting Help: getting-help.md

extra_css:
  - stylesheets/extra.css

theme:
  palette:
    - primary: black
    - accent: light blue
  name: material 
  custom_dir: overrides
  font:
    text: Inter
  favicon: img/favicon.png
  logo: img/logo-for-dark.png
  icon:
    admonition:
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes

markdown_extensions:
  - meta
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.details

extra: 
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datadistillr/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/datadistillr
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC4bsXaNJ8BYt4bP2Ab02j4w
  generator: false
  homepage: https://www.datadistillr.com/


copyright: Copyright &copy; 2021 DataDistillr

